In [1]:
pip install numpy

In [2]:
import numpy as np

# NumPy Array

In [4]:
arr=np.array([1,2,3,4])

# Array operation

In [5]:
arr=np.array([1,2,3,4])
print(arr+2)

[3 4 5 6]


In [7]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)

[ 6  8 10 12]


In [8]:
arr=np.array([1,2,3])
print(arr*2)

[2 4 6]


In [9]:
print(arr+2)

[3 4 5]


In [10]:
print(arr-2)

[-1  0  1]


In [11]:
print(arr/2)

[0.5 1.  1.5]


# indexing and slicing

In [12]:
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [13]:
arr=np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [15]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,2])

6


# mathematical function

In [16]:
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))


15
3.0
1.4142135623730951


# Matrix Operation

In [17]:
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2))

[[19 22]
 [43 50]]


In [20]:
matrix=np.array([[1,2],[3,4]])
values, vectors=np.linalg.eig(matrix)

# Random Module

In [21]:
print(np.random.rand(3))
print(np.random.randint(0,10,5))

[0.88867557 0.16336133 0.64817464]
[0 1 3 2 8]
